name: Action Bootstrap
branding:
  icon: arrow-right-circle
  color: gray-dark
description: |
  This action performs git repo checkout, configures AWS credentials, logs into ECR and generates the image name

inputs:
  ecr-repo-name:
    required: false
    default: ''
  role-to-assume:
    required: true
  role-session-name:
    required: true
  aws-region:
    required: true
  aws-account-id:
    required: true

outputs:
  ecr-repo-name:
    description: 'The generated ECR repository name'
  semver-static:
    description: 'The semantic version'
  semver-list:
    description: 'A list of tags that apply to the current version'
  docker-tags-list:
    description: 'A list of docker image tags with versions'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      if: (!(github.event_name == "pull_request" && (github.event.action == "closed" || github.event.action == "unlabeled")))
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: ${{ inputs.role-session-name }}
        aws-region: ${{ inputs.aws-region }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Image Name
      id: img-name
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "ecr-repo-name=${{inputs.aws-account-id}}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/alpha-image/${{ inputs.ecr-repo-name }}" >>"${GITHUB_OUTPUT}" 
        else
          echo "ecr-repo-name=${{inputs.aws-account-id}}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/image/${{ inputs.ecr-repo-name }}" >>"${GITHUB_OUTPUT}" 
        fi
    - name: Tag Generator
      id: tags
      if: (!(github.event_name == "pull_request" && (github.event.action == "closed" || github.event.action == "unlabeled")))
      uses: hey-car/action-tag-maker@v1.1.6
      with:
        docker-image-name: "${{ steps.img-name.outputs.ecr-repo-name }}"
        pr-number: "${{ github.event.pull_request.number }}"
