---
name: Update major version tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  major-version-tag:
    runs-on: ubuntu-latest
    steps:
      
      - name: Update major version tag
        env:
          GH_TOKEN: ${{ secrets.VERSIONING_TOKEN }}
          REPO: ${{ github.repository }}
          TAG: "${{ github.event.push.ref }}"
        run: |
          _clean_tag="$(echo ${TAG} | cut -d/ -f3)"
          _major_tag="$(echo ${_clean_tag} | cut -d. -f1)"
          _commit_sha="${{ github.event.push.after }}"

          echo "Attempting to delete major version tag ${_major_tag}..."
          gh release delete "${_major_tag}" --repo ${REPO} --cleanup-tag -y || echo "No major version tag to delete"

          echo "Creating major version tag ${_major_tag} for commit ${_commit_sha}..."
          gh release create "${_major_tag}" --repo ${REPO} --target "${_commit_sha}" --generate-notes --latest
          
