---
name: Update major version tag

on:
  release: 
    types:
      - released
      - edited
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
    branches-ignore:
      - '**'
    paths-ignore:
      - '**'

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Actions-R-Us/actions-tagger@v2
        with:
          token: ${{ secrets.VERSIONING_TOKEN }}
